insert into skills values
	('',"https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Typescript_logo_2020.svg/2048px-Typescript_logo_2020.svg.png","Typescript"),
    ('',"https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Database-mysql.svg/640px-Database-mysql.svg.png","MySQL"),
    ('',"https://reactiveprogramming.io/_next/image?url=%2Fbooks%2Freactive-programming%2Ftechs%2Fmongodb.png&w=256&q=75","MongoDB"),
    ('',"https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Postgresql_elephant.svg/1200px-Postgresql_elephant.svg.png","PostgreeSQL"),
	('',"https://cdn-icons-png.flaticon.com/256/174/174854.png","HTML5"),
    ('',"https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/CSS3_logo.svg/240px-CSS3_logo.svg.png","CSS3"),
	('',"https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Angular_full_color_logo.svg/800px-Angular_full_color_logo.svg.png","Angular"),
    ('',"https://www.manualweb.net/img/logos/java.png","Java"),
    ('',"https://blog.chuidiang.org/wp-content/uploads/spring-boot.png","Spring boot"),
    ('',"https://static-00.iconduck.com/assets.00/python-icon-512x512-48og66bp.png","Python"),
    ('',"https://pathfortune.com/wp-content/uploads/2022/05/pngegg-41.png","Django"),
    ('',"https://icons.veryicon.com/png/o/business/vscode-program-item-icon/javascript-3.png","Javascript"),
    ('',"https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/React.svg/1200px-React.svg.png","React"),
    ('',"https://miro.medium.com/v2/resize:fit:800/1*v2vdfKqD4MtmTSgNP0o5cg.png","Nodejs"),
    ('',"https://www.drupal.org/files/project-images/nextjs-icon-dark-background.png","Nextjs"),
    ('',"https://www.britefish.net/wp-content/uploads/2019/07/logo-c-1.png","C"),
	('',"https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/ISO_C%2B%2B_Logo.svg/1200px-ISO_C%2B%2B_Logo.svg.png","C++"),
	('',"https://desarrolloweb.com/storage/tag_images/actual/BzOL16MEqsKOe0VThjF6FXPBi0uyK16lkTety9Wz.png","C#"),
    ('',"https://seocom.agency/wp-content/uploads/2019/02/bootstrap-stack.png","Bootstrap"),
    ('',"https://cdn.jsdelivr.net/gh/angular-material-extensions/pages@master/assets/angular-material-extensions-logo.png","Angular material"),
    ('',"https://cdn.icon-icons.com/icons2/2699/PNG/512/tailwindcss_logo_icon_167923.png","TailwindCSS"),
    ('',"https://victorroblesweb.es/wp-content/uploads/2018/04/git.png","Git"),
    ('',"https://upload.wikimedia.org/wikipedia/commons/c/c2/GitHub_Invertocat_Logo.svg","Github"),
    ('',"https://cdn.worldvectorlogo.com/logos/postman.svg","Postman"),
    ('',"https://marketplace.donweb.com/_next/image?url=https%3A%2F%2Fcloudapps.donweb.com%2Fassets%2F5208bbb7-6c0c-4f8e-b997-c3d7c70b2056%3Ffit%3Doutside&w=256&q=75","Docker")
